package com.ypkim.pinbabel.influenceranalysis.application.domain.error;

public enum InfluencerAnalysisInternalCode {

	PERIOD_START_REQUIRED("PIN-IAN-0001"),
	PERIOD_END_REQUIRED("PIN-IAN-0002"),
	PERIOD_TIMEZONE_REQUIRED("PIN-IAN-0003"),
	INVALID_PERIOD_ORDER("PIN-IAN-0004"),
	PLATFORM_REQUIRED("PIN-IAN-0005"),
	INFLUENCER_REQUIRED("PIN-IAN-0006"),
	PERIOD_REQUIRED("PIN-IAN-0007"),
	MARKET_CODES_REQUIRED("PIN-IAN-0008"),
	POST_FIXTURE_READ_FAILED("PIN-IAN-0009"),
	INSTRUMENT_FIXTURE_READ_FAILED("PIN-IAN-0010"),
	POST_ID_REQUIRED("PIN-IAN-0011"),
	POST_PLATFORM_REQUIRED("PIN-IAN-0012"),
	POST_AUTHOR_REQUIRED("PIN-IAN-0013"),
	POST_PUBLISHED_AT_REQUIRED("PIN-IAN-0014"),
	POST_URL_REQUIRED("PIN-IAN-0015"),
	POST_TEXT_REQUIRED("PIN-IAN-0016"),
	POST_SOURCE_REQUIRED("PIN-IAN-0017"),
	POST_KIND_REQUIRED("PIN-IAN-0018"),
	POSTS_REQUIRED("PIN-IAN-0019"),
	POST_ITEM_REQUIRED("PIN-IAN-0020"),
	TOO_MANY_POSTS("PIN-IAN-0021"),
	INSTRUMENT_ID_REQUIRED("PIN-IAN-0022"),
	TICKER_REQUIRED("PIN-IAN-0023"),
	EXCHANGE_REQUIRED("PIN-IAN-0024"),
	DISPLAY_NAME_REQUIRED("PIN-IAN-0025"),
	ALIASES_REQUIRED("PIN-IAN-0026"),
	ASSESSMENT_POST_ID_REQUIRED("PIN-IAN-0027"),
	ASSESSMENT_SENTIMENT_REQUIRED("PIN-IAN-0028"),
	ASSESSMENT_RATIONALE_REQUIRED("PIN-IAN-0029"),
	ASSESSMENT_CANONICAL_PAIR_REQUIRED("PIN-IAN-0030"),
	ASSESSMENT_CANONICAL_INSTRUMENT_REQUIRED("PIN-IAN-0031"),
	ASSESSMENTS_REQUIRED("PIN-IAN-0032"),
	ASSESSMENT_ITEM_REQUIRED("PIN-IAN-0033"),
	ASSESSMENT_POST_NOT_FOUND("PIN-IAN-0034"),
	ASSESSMENT_INSTRUMENT_NOT_FOUND("PIN-IAN-0035"),
	ASSESSMENT_TICKER_MISMATCH("PIN-IAN-0036"),
	ASSESSMENT_MARKET_NOT_ALLOWED("PIN-IAN-0037"),
	LLM_API_KEY_REQUIRED("PIN-IAN-0038"),
	LLM_BASE_URL_REQUIRED("PIN-IAN-0039"),
	LLM_BASE_URL_INVALID("PIN-IAN-0040"),
	LLM_VALIDATION_FAILED("PIN-IAN-0041"),
	ANALYSIS_REPORT_SERIALIZATION_FAILED("PIN-IAN-0042"),
	ANALYSIS_REPORT_SCHEMA_UNSUPPORTED("PIN-IAN-0043"),
	ANALYSIS_REPORT_DESERIALIZATION_FAILED("PIN-IAN-0044"),
	ANALYSIS_RUN_SAVE_FAILED("PIN-IAN-0045"),
	ANALYSIS_TRACE_APPEND_FAILED("PIN-IAN-0046"),
	ANALYSIS_RUN_QUERY_FAILED("PIN-IAN-0047");

	private final String value;

	InfluencerAnalysisInternalCode(String value) {
		this.value = value;
	}

	public String value() {
		return value;
	}
}
